### ISSUE TITLE
Update to take advantage of new MQTT logging in Rack32 lib (v1.8.0+)

### ISSUE THREAD

**Issue by sumnerboy12** [SuperHouse/OXRS-SHA-StateIO-ESP32-FW#6]
I have updated the State Monitor/Controller firmware but thought I would leave this for you, since it is your baby ;) and so you can see what I have done first hand and make sure it looks alright.

Any questions let me know.

**Comment by moinmoin-sh** [comment]
fixed in release 3.11.0
